In [1]:
import torch
from torchvision.models import vgg16,VGG16_Weights
from torch import nn
import numpy as np
import os
# import matplotlib.pyplot as plt

In [2]:
model=vgg16(weights=VGG16_Weights.IMAGENET1K_V1)

In [13]:
in_ten=torch.rand(size=(100,3,32,32))

In [3]:
soft=nn.Softmax(dim=1)


In [4]:
transformer=VGG16_Weights.IMAGENET1K_V1.transforms()

In [5]:
from PIL import Image


In [6]:
import subprocess

In [7]:
img=Image.open('/var/DSTeam/locnt2/personal/logo_generator/data/LLD_favicons_full_png/050669.png')

In [8]:
img_=transformer(img)

In [9]:
f_label=open('/var/DSTeam/locnt2/personal/logo_generator/data/label.txt','a')

In [10]:
import json

In [22]:
file_label=open('/var/DSTeam/locnt2/personal/logo_generator/data/label.txt','w')

In [23]:
def write_immediate(f):
    f.flush()
    os.fsync(f.fileno())


In [13]:
directory = '/var/DSTeam/locnt2/personal/logo_generator/data/LLD_favicons_full_png/'
images_name=[]
for i,file in enumerate(os.listdir(directory)):
    images_name.append(file)
    if i > 256000:
        break

In [14]:
len(set(images_name))

256002

In [24]:
directory = '/var/DSTeam/locnt2/personal/logo_generator/data/LLD_favicons_full_png/'

# iterate over files in
# that directory
batch_size=256
num_batchs=1000
list_batch_images=[]
batch_image_file_names=[]
tmp_batch=np.empty(shape=(1,3,32,32))
count=0
num_batch_so_far=0
for filename in os.listdir(directory):
    f = os.path.join(directory, filename)
    # checking if it is a file
    if os.path.isfile(f):
        img=Image.open(f)
        this_img_toarr=np.array(img).reshape(1,3,32,32)
        tmp_batch=np.concatenate([tmp_batch,this_img_toarr],axis=0)

        batch_image_file_names.append(filename)
        count+=1
    if count==batch_size:
        print('start')
        transformed=transformer(
            torch.from_numpy(tmp_batch[1:])
        )
        with torch.no_grad():
            pred=model(transformer(transformed))

        highest_prob_5_idx=torch.argsort(soft(pred),descending=True)[:,:5]
        
        prob_pred=soft(pred)
        highest_prob_5=prob_pred.gather(dim=1, index=highest_prob_5_idx).tolist()
        highest_prob_5_idx=highest_prob_5_idx.tolist()

        for i in range(batch_size):
            file_label.write(';'.join(
                    [
                        batch_image_file_names[i],
                        str(highest_prob_5_idx[i]),
                        str(highest_prob_5[i])
                    ]
                )
            )
            file_label.write('\n')
    
        write_immediate(file_label)


        # file_label.write('\n'.join(
        #     list(map(
        #         lambda x:str(x),
        #         torch.argsort(pred,descending=True)[:,:5].tolist()
        #         ))
        #     )      
        # )
        # file_label.write('\n')
        # write_immediate(file_label)
        
        tmp_batch=np.empty(shape=(1,3,32,32))
        batch_image_file_names=[]
        count=0
        num_batch_so_far+=1
        if num_batch_so_far==num_batchs:
            break
        # break
    

start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
start
star

In [160]:
highest_prob_5

tensor([[818, 663, 671, 670, 669],
        [818, 663, 671, 670, 669],
        [904, 671, 657, 658, 659],
        ...,
        [818, 663, 671, 670, 669],
        [828, 664, 671, 670, 669],
        [409, 671, 657, 658, 659]])

In [169]:
prob_pred.gather(dim=1, index=highest_prob_5)

tensor([[1., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0.],
        ...,
        [1., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0.],
        [1., 0., 0., 0., 0.]])

In [146]:
prob_pred[1].sum()

tensor(1.)

In [157]:
prob_pred[:,highest_prob_5[:,:]]


IndexError: too many indices for tensor of dimension 1

In [158]:
highest_prob_5

tensor([1.0000e+00, 1.3375e-26, 0.0000e+00, 0.0000e+00, 0.0000e+00])

In [147]:
highest_prob_5.shape

torch.Size([256, 5])

In [30]:
with torch.no_grad():
    pred=model(transformer(torch.from_numpy(tmp_batch[1:])))

In [55]:
f.write('\n'.join(
    list(map(
        lambda x:str(x),
        torch.argsort(pred,descending=True)[:,:5].tolist()
        ))
    )      
)

259

In [8]:
import itertools
a = [1, 50]
b = [2, 2000]
for a,b in itertools.ar_product(a,b):
    print(a,b)

AttributeError: module 'itertools' has no attribute 'ar_product'

In [4]:
if all([0,1,2]):
    print("df")

In [56]:
f.close()

In [35]:
transformer(tmp_batch)

TypeError: img should be PIL Image. Got <class 'list'>

In [20]:
ans[0][5]

tensor(1.4860e-05, grad_fn=<SelectBackward0>)

In [31]:
ans[0][244]

tensor(0.0993, grad_fn=<SelectBackward0>)

In [3]:
if list([0,2,1]):
    print('adsf')

adsf


In [30]:
ans.argsort(descending=True)

tensor([[244, 164, 247, 194, 175, 241, 165, 255, 200, 243, 163, 220, 240, 238,
         167, 208, 234, 256, 239, 212, 246, 216, 166, 236, 152, 161, 168, 377,
         214, 160, 210, 207, 262, 235, 154, 174, 190, 252, 380, 362, 206, 257,
         162, 242, 383, 219, 364, 202, 297, 507, 198, 229, 232, 181, 222, 228,
         261, 254, 368, 251, 159, 205, 370, 183, 227, 382, 249, 676, 221, 158,
         248, 292, 282, 170, 179, 371, 281, 233, 226, 156, 204, 358, 375, 264,
         197, 176, 193, 209, 852, 188, 743, 155, 722, 384, 177, 215, 182, 225,
         180, 231, 187, 273, 522, 771, 275, 369, 195, 260, 680, 335, 157, 178,
         267, 534, 217, 577, 379, 268, 482, 426, 686, 185, 361, 789, 736, 250,
         811, 740, 585, 269, 196, 387, 359, 224, 223, 699, 265, 290, 299, 367,
         169, 201, 589, 366, 266, 237, 747, 103, 285, 731, 378, 186,  87, 374,
         805, 779, 253, 272, 213, 365, 356, 211, 388, 230, 763, 720, 691, 539,
         294, 373, 494, 761, 191, 844, 341, 481, 542

In [107]:
ans=soft(model(transformer(img).reshape(1,3,224,224)))

In [119]:
import json

In [121]:
e=json.dumps(ans.detach().numpy().flatten().tolist())

In [122]:
eval(e)

[2.7339038410900685e-07,
 4.93646803079173e-05,
 3.116128155511433e-08,
 2.7174690941933477e-08,
 7.021175196797458e-09,
 2.025496314672637e-06,
 2.2733024351850872e-09,
 5.8235986699628484e-08,
 2.5075117093820154e-08,
 4.0595764971840254e-08,
 3.7993146406734013e-07,
 4.242301443468932e-08,
 8.224457559435905e-08,
 7.827489767464613e-09,
 2.658751157014194e-07,
 4.007087994750691e-08,
 2.619838710415934e-07,
 1.562757034889728e-08,
 4.731647518241289e-09,
 1.790910175714089e-08,
 7.096381704485566e-09,
 2.8959545872453418e-08,
 9.90344606321969e-09,
 5.4653854775210675e-09,
 1.472255206635964e-08,
 1.0868620847759303e-07,
 8.731904586056771e-07,
 1.6728045011404902e-05,
 2.7902151487069204e-06,
 4.8549527491559274e-06,
 3.671602044619249e-08,
 1.0080607353302184e-06,
 3.255720685046981e-06,
 5.352363530164439e-08,
 6.124109575011971e-08,
 4.9754575570659654e-08,
 2.6547607490101655e-07,
 1.3903956208594082e-08,
 1.3839530765835661e-06,
 1.221467584855418e-07,
 1.0761069546560975e-07,

In [49]:
torch.topk(ans.flatten(), 3).indices


tensor([530, 398, 439])